#!/bin/zsh
}

_fzf_menu() {
  _entries() { for i in ${dir_index[@]}; do echo ${USER_DIRS[$i]}; done; }
  _parse_opt() { OPT[2]+="${SYM_OFFSET:- }"; }
  _fzf_open() {
    local ignore dir="$1" app="$3"
    local fd_cmd=(fd -tf -H -L -c always)
    local fzf_cmd=(fzf --height=100% -m --ansi --preview=\"preview {}\" --prompt=\"$2\")
    local xargs_cmd=(xargs -ro -d \'\\n\' "$app")
    [[ $dir='/' ]] && ignore=(--ignore-file ~/.config/fd/root); cd $dir
    local res=`eval ${fd_cmd[@]} ${ignore[@]} | eval ${fzf_cmd[@]}`
    local detach=$([[ $app =~ ".*vim|emacs(client)?" ]] || echo " & disown")
    [[ -n $res ]] && IFS='' && {
      echo $res | eval "${xargs_cmd[@]} $detach"
    }; unset IFS
    cd -; zle reset-prompt 2>/dev/null; zle-line-init 2>/dev/null
  }
  OPT=(`_entries | fzf --height=100% --prompt="Open: " --with-nth 2,4..`)
  [[ -n $OPT ]] && { _parse_opt; _fzf_open ${OPT[@]}; } || zle reset-prompt 2>/dev/null
}

source ~/.config/zsh/user/dirs.zsh
